
title: My Resume
url: 'https://kilo0103.github.io/'
baseurl: '' #change it according to your repository name



# Profile information
yourname: Youngjoong Kim  ## put your name
title: 'Programmer'  ## your title
location: Suwon , KR


## Social Profiles
facebook: https://www.facebook.com/profile.php?id=100014872834942  ## your facebook account url
##twitter: http://www.twitter.com  ## your twitter account url
##linkedin: http://www.linkedin.com  ## your linkedin account url
##dribbble: http://www.dribble.com  ## you dribbble account url
##foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
